# Generated by Django 4.0.5 on 2022-06-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pwd_activity',
            field=models.BooleanField(default=False, verbose_name='是否加密'),
        ),
    ]
