# Generated by Django 4.0.5 on 2022-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_navs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='login_date',
            field=models.DateTimeField(auto_now=True, verbose_name='登录时间'),
        ),
    ]
