# Generated by Django 4.0.5 on 2022-06-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_userinfo_login_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='login_date',
        ),
    ]
